# Generated by Django 4.0 on 2022-02-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_category_options_article_auther_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
