# Generated by Django 4.0 on 2022-04-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
